version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: almedia-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: offers_db
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d offers_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - node-server
  # app:
  #   build: .
  #   container_name: almedia-app
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: admin
  #     DB_NAME: offers_db
  #     OFFER1_URL: http://node-server:3000/offers1
  #     OFFER2_URL: http://node-server:3000/offers2
  #   depends_on:
  #     - db
  #     - node-server

  node-server:
    build: ./node_server
    container_name: almedia-node-server
    ports:
      - "3000:3000"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:3000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
    